spring:
  application:
    name: SpringAppWithMonitoring
    
  profiles:
    active: development
    
server:
  port: 8080    
 
info:
  app:
    name: SpringDemoAppWithMonitoring 
    description: Spring Demo to show monitoring with prometheus and grafana
    version: 1.0.0
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active} 
      
  endpoint:
    shutdown:
      enabled: true                      